### ISSUE TITLE
Add ORCID to metadata display

### ISSUE THREAD

**Issue by ihardy** [WRLC/ORCID-Create-on-demand#12]

**Comment by krebeck** [comment]
Completed on auislandora-dev.  Shown here: http://auislandora-dev.wrlc.org/islandora/object/auislandora%3A156

**Comment by dongourley** [comment]
See these display guidelines: https://orcid.org/trademark-and-id-display-guidelines

**Comment by dongourley** [comment]
Is it possible to conditionally display the identifier if and only if it is an ORCID identifier -- not an email address?

**Comment by krebeck** [comment]
No way to conditionally display.  At least not without changing base code.  Metadata display grabs whatever is in MADS_u1_ms field.  There are no validation options in display.  We could add validation options to the XML form, but that might only work for manual data entry.

**Comment by dongourley** [comment]
@krebeck, if you are following the ORCID display guidelines and showing the orcid.org/ domain then I think you can remove ORCID from the field tag and just say "Identifier" -- it will be clear from the value which kind of identifier it is.

In any case, I think you can close this issue.

**Comment by krebeck** [comment]
Okay, I have just called it "Identifier"
