### ISSUE TITLE
Create RESTful web service to implement islandora api calls

### ISSUE THREAD

**Issue by ihardy** [WRLC/ORCID-Create-on-demand#14]
Post user data to service, service will execute API calls documented here: https://github.com/WRLC/ORCID-Create-on-demand/issues/4

**Comment by dongourley** [comment]
Currently, I am writing the ORCID info to a flat file. Attached is the current "database". Think about how you want me to transfer this info to your web service:
- as part of the the create/update islandora request?
- in a new save-orcid-access-info request?
- by writing it to your MongoDB?
[db.json.txt](https://github.com/WRLC/ORCID-Create-on-demand/files/1350060/db.json.txt)

**Comment by ihardy** [comment]
I'm mocking this service up now. I like the first option: posted as json in the body of an http request. in curl the request might look something like this:
```
curl -XPOST scheme://servicename.tld/api/endpoint \
  -H 'content-type: application/json' \
  -d '{
             "orcid":"XXXXX",
             "access-token": "XXXXX",
             "etc": "...",
      }'
```

**Comment by ihardy** [comment]
API should take two calls, one to create/update orcid. One to request the creation of a scholar in audra.

**Comment by dongourley** [comment]
Per our conversation yesterday: we will have two calls (endpoints) for this service....1) will store the orcid info, including access-token, refresh-token and stuff; and 2) will update AUDRA-IR with the ORCID record information. (this is just repeating what you just put in a comment ...)

Plan eventually for an endpoint that will retrieve the access-token for an ORCID iD, but I don't think we need it for this project...unless there is some reason to make it a two step process (e.g. we want to ask user before updating their AUDRA-IR profile).

**Comment by ihardy** [comment]
Initial Commit for REST API service: https://github.com/WRLC/orcid_task_service
