### ISSUE TITLE
Islandora API calls to create a citation object

### ISSUE THREAD

**Issue by dongourley** [WRLC/ORCID-Create-on-demand#16]
Document the API call(s) that will create a citation object like [this one](http://auislandora.wrlc.org/islandora/object/auislandora%3A70221?solr_nav%5Bid%5D=1374c36f358fc6a7e64f&solr_nav%5Bpage%5D=0&solr_nav%5Boffset%5D=5) (no document PDF attached).

Here is an example of the MODS XML for a citation:
http://auislandora-dev.wrlc.org/islandora/object/ir%3A7/datastream/MODS/view

I will provide a JSON representation of this to the orcid_task_service and Ian will make the API call to create the citation. He will also need a way of checking whether the citation already exists in Islandora. This could use one of the citation identifiers, like DOI, but do we need a fallback in case none of the identifiers are in ORCID? In that case we could use the ORCID "put-code" but that may result in duplicates. I can include the put-code, but what would be the MODS identifier type for it?

**Comment by ihardy** [comment]
## Check for existing citations
Search for existing citations RESEARCHER_DISPLAY_NAME should be whatever was in the researcher's mods before it was updated with an ORCID.

```
GET https://HOSTNAMEislandora/rest/v1/solr/mods_name_personal_author_displayForm_ms:RESEARCHER_DISPLAY_NAME&rows=50
```

## Matching existing citations with results from ORCID API
This is where it gets problematic, can use DOI, but it's not required in the orcid work metadata (example below)

Solr result:
http://auislandora-dev.wrlc.org:8080/solr/collection1/select?q=mods_name_personal_author_displayForm_ms%3Askramer*&rows=1&wt=xml&indent=true
Orcid result:
[orcid_result.txt](https://github.com/WRLC/ORCID-Create-on-demand/files/1668419/orcid_result.txt)

## Creating Citations
1. create an object for each citation:
```
POST https://HOSTNAME/islandora/rest/v1/object
data = {
    "namespace" :"auislandora",
    "label" : label,
    "owner" : "admin"
}
```
2. Add a rels-ext
```
POST https://HOSTNAME/islandora/rest/v1/object/PID/relationship
data = {
    "uri":"info:fedora/fedora-system:def/model#",
    "predicate":"hasModel",
    "object":"ir:citationCModel",
    "type":"uri"
}
```
3. post MODS
```
POST https://HOSTNAME/islandora/rest/v1/object/PID/datastream
data = {
        'dsid': 'MODS',
        'controlGroup': 'M',
}
files = {'mods.xml': MODS_XML_FILE}
```

**Comment by dongourley** [comment]
I don't think we need to create citations (and worry about existing ones) for researchers whose MODS profiles are being updated (already exist in AUDRA). I also think for this demo we don't need to worry about citations we create for new researcher profiles that might match publications that are already in AUDRA-IR.

**Comment by ihardy** [comment]
Great, I'll just add every citation I get back from ORCID when I'm creating a new profile, and just update the ids for people + works that already exist.
