### ISSUE TITLE
Have user go through aladin-sp before being redirected to ORCID

### ISSUE THREAD

**Issue by dongourley** [WRLC/ORCID-Create-on-demand#3]
Currently index.html sends user to the so-called "fancy url" to create/connect their ORCID iD.
Need to change that to send them to aladin-sp, have them login to idp.american.edu, and then redirect to ORCID. 

https://aladin-tst.wrlc.org/simplesamlphp/wrlcauth/orcidlogin.php?institution=au&url=<fancyurl>

orcidlogin.php will be created by [WRLC/Aladin-SP/#17](https://github.com/WRLC/Aladin-SP/issues/17)

![orcid create-on-demand](https://user-images.githubusercontent.com/282597/29091895-5a167bde-7c52-11e7-8f89-f823e7de48e1.png)

**Comment by ihardy** [comment]
Implement in the Aladin-SP software. Ticket at WRLC/Aladin-SP#17

**Comment by ihardy** [comment]
https://github.com/WRLC/Aladin-SP/tree/t17-orcid-auth
