### ISSUE TITLE
Islandora API calls to create/update personCModel object

### ISSUE THREAD

**Issue by dongourley** [WRLC/ORCID-Create-on-demand#4]
Install API module on sandbox & stage (done).
https://github.com/discoverygarden/islandora_rest

Test calls on the sandbox...Ian recommends Postman for testing API calls when cURL gets klunky.
https://www.getpostman.com/

Layout the series of calls needed for:

1. searching to see if a user has a personCModel object in Islandora
2. if so, updating it to include ORCID iD
3. if not creating a personCModel object with user's name, email, ORCID iD, other (e.g. link to CFM page)?

Provide basic MADS JSON format for creating and updating the personCModel object. Can/should we store additional info there, such as the results from the ORCID authorization?
![orcid create-on-demand 1](https://user-images.githubusercontent.com/282597/29123730-ba44279e-7ce4-11e7-92f4-f66ff944c66e.png)

**Comment by dongourley** [comment]
@ihardy, please assign this to @krebeck

**Comment by krebeck** [comment]
Some more information about using ORCIDs to link person entities with other content models:

How to Connect a Person Entity with Citation or Thesis objects
Connecting is done by string match on an identifier.
Create the Person Entity with the MADS Scholar Form.
In the MADS Scholar Form, in the field for "Identifier", enter a controlled value.  (The "Identifier" form field stores to MADS as <identifier type="u1">.)  You will use this identifier later to link citation objects, by entering the same identifier in with author information on a Citation or Thesis object.  (Tip:  Before beginning, pick a system for assigning these identifiers.  A good idea would be to use an existing authority control system, such as university assigned email addresses or Orcid IDs, and use these consistently in your repository.)
Note: If you link a Citation object to a Person entity, then you change the Person's identifier, the link from the Citation object will break.  So, you need to pick the system for assigning identifiers before you begin to create Person entities.
Create a Citation object.  In the Citation MODS Form, in the Author information in the field for "Qualified Name", enter the identifier that you used when you created the Person Entity for the author.  (The "Qualified Name" form field stores to MODS as <displayForm>.)
Now, when you view the Person Entity which you created in step 1, you will see the Citation object show up under "Recent Citations" for the person.

**Comment by ihardy** [comment]
example auth & read reqs w/python for testing: https://gist.github.com/ihardy/1e6c12532e58b40ce5244cae62f094ee

**Comment by ihardy** [comment]
@krebeck Can you paste your steps to create a new object here (sanitized of any sensitive information)

**Comment by krebeck** [comment]
## if running the CURL requests from Islandora servers, must reference full path of curl as in /usr/bin/curl --verbose --cookie-jar ./cookies.txt -X POST -H "Content-Type: multipart/form-data" -F "name=useradmin" -F "pass=userpass" -F "form_id=user_login" -F "op=Log in" "http://auislandora-dev.wrlc.org/user/login" ##
## Step 1 Authenticate to Rest API ##
curl --cookie-jar ./cookies2.txt -X POST -H "Content-Type: multipart/form-data" -F "name=useradmin" -F "pass=userpass" -F "form_id=user_login" -F "op=Log in" "http://auislandora-dev.wrlc.org/user/login"
## Step 2 Test a GET function [optional] ##
curl -b ./cookies.txt "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:73"
## Step 3 Search for User in Islandora Based on Email Address ##
curl -b ./cookies.txt -H "Accept:application/json" "http://auislandora-dev.wrlc.org/islandora/rest/v1/solr/MADS_email_ms:username@american.edu"
## Step 4 If Name Not Found, Create A New Object ##
curl -b ./cookies.txt -H "Accept: application/json" -X POST "http://auislandora-dev.wrlc.org/islandora/rest/v1/object" -d '{"pid":"auislandora:1503","label":"Person Name","owner":"admin"}'
## Step 5 Modify the Object's Properties (useful to put object in inactive state) [optional but suggested] ##
curl -b ./cookies.txt -H "Content-Type: application/json" -X PUT "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1506" -d '{"label":"new name","owner":"admin","state":"I"}'
## Step 6 Begin Building RELS-EXT datastream via a series of relationship changes ##
curl -v -b ./cookies.txt -X POST -H "Accept: application/json" -d '{"uri":"info:fedora/fedora-system:def/model#","predicate":"hasModel","object":"islandora:personCModel","type":"uri"}' "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1508/relationship"
## Step 7 Continue with Above but string together if possible ##
curl -v -b ./cookies.txt -X POST -H "Accept: application/json" -d '{"uri":"info:fedora/fedora-system:def/relations-external#","predicate":"isMemberOfCollection","object":"ir:bios","type":"uri"}' "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1508/relationship"
## Step 8 Create MADS datastream using template file ##
curl -v -b ./cookies.txt -X POST -H "Content-Type: multipart/form-data" -F "dsid=MADS" -F "controlGroup=M", -F "multipart file as request content=@/home/user/MADS_Record.xml" "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1508/datastream"
## Step 9 Create TN datastream using generic image ##
curl -v -b ./cookies.txt -X POST -H "Content-Type: multipart/form-data" -F "dsid=TN" -F "controlGroup=M", -F "multipart file as request content=@/home/user/thumbnail.jpg" "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/auislandora:1508/datastream"
## Step 10 Describe MADS Datastream (ORCID to be injected in <identifier type="u1">field) ##
curl -b ./cookies.txt -H "Accept:application/json" "http://auislandora-dev.wrlc.org/islandora/rest/v1/obislandora:1508/datastream/MADS?content,true"

**Comment by dongourley** [comment]
I am reopening this issue to add additional requirements. In addition to creating or updating the personCModel object (MADS datastream) in islandora, including changing the "u1" identifier to the ORCID iD, we need the steps to:

1. search for any objects in AUDRA-IR that are linked to the scholar by old "u1" identifier (aka email address) and change the displayForm in the MODS for that object to ORCID iD
1. create citation objects for works (publications) that are retrieved from ORCID and link to user by ORCID iD

**Comment by dongourley** [comment]
Also, I don't know if it belongs in this issue or a separate one, but is there a way, when creating a new personCModel object, to include the Solr view of "recent citations"? Or is that controlled by the Islandora/Drupal way of displaying the MADS on a scholar profile page?

**Comment by krebeck** [comment]
1a.  A search for objects in AUDRA that are linked by the old u1 identifier would take the following form:

curl -b ./cookies.txt -H "Accept:application/json" "http://auislandora-dev.wrlc.org/islandora/rest/v1/solr/mods_name_personal_displayForm_mt:username@email.edu"

1b. Changing the displayForm in the MODS for that object to ORCID iD

My first thought was that we could use a PUT request to modify and existing datastream's content, but I think the best way to do this will be to read the output of the existing MODS, replace what's between the <displayForm> tags, save a copy and then POST this new MODS similar to step 8 above.

**Comment by krebeck** [comment]
1b. (continued)
So the workflow would be to do something like 
curl -g -b ./cookies.txt "http://auislandora-dev.wrlc.org/islandora/rest/v1/object/ir:7/datastream/MODS"

This would return the xml of the current MODS datastream's content (not to be confused with its properties).  In that would be a section that looks like this:

```
<name type="personal">
    <role>
      <roleTerm authority="marcrelator" type="text">author</roleTerm>
    </role>
    <namePart type="given">Stefan</namePart>
    <namePart type="family">Kramer</namePart>
    <displayForm>skramer@american.edu</displayForm>
    <affiliation></affiliation>
    <nameIdentifier></nameIdentifier>
  </name>
```

We would replace what's currently between the displayForm tags with an ORCID like https://orcid.org/0000-0001-5795-7629, save and then PUT this new file.  Although I think a POST as in Step 8 above would also work because with Fedora versioning, there's no real difference between POSTing and new version and PUTting a change (which will also create a new version).

**Comment by ihardy** [comment]
question for @krebeck, do I need to kick off some solr indexing job after creating a new object in islandora. I've created lots from testing api calls but they aren't showing up in this list:

http://auislandora-dev.wrlc.org/admin/islandora/tools/simple_workflow/list

Here's an example person http://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1538

**Comment by krebeck** [comment]
The simple workflow list only shows objects that are in an inactive state.
My instructions included a parameter to make objects inactive as a possible
option so that library staff could review these bios before making them
show up for patrons.  You can see that option on the properties page here:
http://auislandora-dev.wrlc.org/islandora/object/auislandora%3A1538/manage/properties

So active objects won't show up in the list, only inactive ones.  If you
look at the collection level
<http://auislandora-dev.wrlc.org/islandora/object/ir%3Abios?page=1>, you'll
see some of the new ones you've created.  Hopefully between the active ones
in the collection view and the simple workflow list of inactive ones, all
are accounted for.

A

Aaron Krebeck
Digital Services Librarian
Washington Research Library Consortium
301-390-2040
