### ISSUE TITLE
Create/update personCModel object in oauth-redirect.php

### ISSUE THREAD

**Issue by dongourley** [WRLC/ORCID-Create-on-demand#5]
Implement the API calls defined by #4

**Comment by krebeck** [comment]
Some of this php may be helpful in mashing some of the relevant curl requests together:  https://github.com/mjordan/islandora_rest_ingester/blob/master/ingest.php

Not created with our use case in mind and with a lot of extraneous bits, but could be helpful.

**Comment by dongourley** [comment]
This is going to be done in a separate web service as described in #14
