### ISSUE TITLE
Sync some test profiles from production to dev

### ISSUE THREAD

**Issue by ihardy** [WRLC/ORCID-Create-on-demand#8]

**Comment by krebeck** [comment]
[I have created a number of test profiles.](http://auislandora-dev.wrlc.org/islandora/object/ir%3Abios)  One is for Aaron Krebeck and can be one of the first test objects to attach my ORCID.  I also added one for Stefan Kramer, Gwendolyn Reece, and Susan McElrath based on AU prod data.  Finally, there are two person objects that I created using only the REST API.  [One is set to active state](auislandora-dev.wrlc.org/islandora/object/auislandora%3A1506) (anonymous users can see it) and one is set to inactive (anons can't see it).
